name: SolasMatchDart
author: spaceindaver
description: The Dart Framework for UI work in SOLAS Match
dependencies:
  browser: any
  crypto: any
  js: any
  json_object: any
  polymer: any
  sprintf: any
  web_components: any
  xml: any
transformers:
- polymer:
    entry_points:
    - web/Routes/Users/home.dart
    - web/Routes/Users/UserPrivateProfile.dart
    - web/Routes/Users/ClaimedTasks.dart
    - web/Routes/Projects/ProjectCreate.dart
- $dart2js:
    checked: true
    minify: false